import type { Config } from 'tailwindcss'

export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c5c6cd',
        'surface-dim': '#d8dadc',
        'primary-fixed-dim': '#bcc7de',
        'on-secondary-fixed': '#00174b',
        'error-container': '#ffdad6',
        'surface': '#f7f9fb',
        'background': '#f7f9fb',
        'on-error-container': '#93000a',
        'surface-container': '#eceef0',
        'primary': '#091426',
        'tertiary-container': '#00301f',
        'on-primary-fixed-variant': '#3c475a',
        'surface-variant': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#b4c5ff',
        'on-tertiary-container': '#24a375',
        'surface-tint': '#545f73',
        'inverse-surface': '#2d3133',
        'tertiary': '#00190e',
        'outline': '#75777d',
        'on-primary-container': '#8590a6',
        'secondary-container': '#316bf3',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-fixed': '#002114',
        'on-surface': '#191c1e',
        'on-secondary-fixed-variant': '#003ea8',
        'error': '#ba1a1a',
        'tertiary-fixed': '#85f8c4',
        'primary-fixed': '#d8e3fb',
        'on-surface-variant': '#45474c',
        'on-error': '#ffffff',
        'on-primary-fixed': '#111c2d',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary-fixed-variant': '#005137',
        'primary-container': '#1e293b',
        'secondary-fixed': '#dbe1ff',
        'tertiary-fixed-dim': '#68dba9',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-bright': '#f7f9fb',
        'on-secondary-container': '#fefcff',
        'inverse-primary': '#bcc7de',
        'on-background': '#191c1e',
        'secondary': '#0051d5',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'sm': '8px',
        'lg': '24px',
        'md': '16px',
        'xl': '40px',
        'xs': '4px',
        'unit': '8px',
        'container-max': '1280px',
        'xxl': '64px',
        'gutter': '24px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'display': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '1.25', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.25', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '600' }],
        'display': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
} as Config
